# Generated by Django 5.1.6 on 2025-02-28 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("person", "0002_person_birthday_contact_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="addresses",
            field=models.ManyToManyField(
                through="person.PersonAddress", to="address.address"
            ),
        ),
        migrations.AddField(
            model_name="personaddress",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PersonPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Mobile", max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="person.person"
                    ),
                ),
            ],
        ),
    ]
