# Generated by Django 5.1.6 on 2025-03-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_options"),
        ("person", "0003_person_addresses_personaddress_created_personphone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personaddress",
            options={"verbose_name_plural": "Person addresses"},
        ),
        migrations.AlterUniqueTogether(
            name="personaddress",
            unique_together={("person", "address")},
        ),
    ]
