# Generated by Django 5.1.6 on 2025-03-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0004_alter_personaddress_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
        migrations.AlterModelOptions(
            name="personphone",
            options={"verbose_name_plural": "Person phone numbers"},
        ),
        migrations.AlterUniqueTogether(
            name="personphone",
            unique_together={("person", "phone")},
        ),
    ]
