# Generated by Django 5.2 on 2025-04-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_person_options_alter_personphone_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name", "first_contact"],
                "verbose_name_plural": "People",
            },
        ),
    ]
