min_version = "2024.9.5"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Set up the path for node module binaries
BIN_PATH = "{{ config_root }}/node_modules/.bin"

[tools]
# Install Node.js using the specified version
node = "20"

# Install some npm packages globally if needed
"npm:typescript" = "latest"
"npm:@angular/cli" = "latest"
qdns = "latest"

[tasks.start]
alias = "s"
description = "Start the development server"
run = "yarn start"

[tasks.test]
description = "Run tests"
alias = "t"
run = "yarn test"

[tasks.build]
description = "Build the project"
alias = "b"
run = "yarn build"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "node: $(node --version)"
'''
